# Generated by Django 5.0.6 on 2024-06-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Available'),
        ),
    ]
