version: '3'

services:
  web:
    build: .
    command: /bin/bash -c "source /workspace/venv/bin/activate && gunicorn --workers 3 myproject.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: defaultdb
      POSTGRES_USER: doadmin
      POSTGRES_PASSWORD: AVNS_B2GpkX922z4qvlPnr95
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgres_data: