version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "while !</dev/tcp/db/5432; do sleep 1; done;
      gunicorn myproject.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=myproject  # Updated to use the new database name
      - POSTGRES_USER=myprojectuser  # Updated to use the new user
      - POSTGRES_PASSWORD=password  # Updated to use the new password
      - POSTGRES_HOST_AUTH_METHOD=trust  # Trust authentication for local connections

volumes:
  postgres_data:
