version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "while !</dev/tcp/db/5432; do sleep 1; done;
      gunicorn myproject.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=defaultdb
      - POSTGRES_USER=doadmin
      - POSTGRES_PASSWORD=AVNS_B2GpkX922z4qvlPnr95
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PORT=25060

volumes:
  postgres_data:
